import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'normalize.css';
import "./globals.css";
import Header from "@/components/Header/Header";
import TanStackProvider from "@/components/TanstackProvider";


import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TanStackProvider>
          <Header />
          {children}
          {/* вот здесь контейнер для тостов */}
          <ToastContainer position="top-right" autoClose={3000} />
        </TanStackProvider>
      </body>
    </html>
  );
}
